### ISSUE TITLE
Vanilla block outlines broken

### ISSUE THREAD

**Issue by SeanLatimer** [LasmGratel/BetterP2P#11]
There's currently an issue causing the vanilla block outlines are entirely overridden, even when not using the card.

They should be returned to vanilla behaviour when not holding the advanced card in hand.

**Comment by LasmGratel** [comment]
This happens only on forge, will be fixed in the next version.

**Comment by LasmGratel** [comment]
Fixed in 1.4.1

**Comment by SeanLatimer** [comment]
> This happens only on forge, will be fixed in the next version.

My apologies, I should have mentioned. We were having this issue on Fabric not Forge.

**Comment by LasmGratel** [comment]
@SeanLatimer Well, I changed render behaviour on both sides so maybe you can try latest version and see if it still occurs
