### ISSUE TITLE
No Recipe for Advanced Memory Card

### ISSUE THREAD

**Issue by AndreCelso** [LasmGratel/BetterP2P#17]
Upon installing and playing with Better P2P on 1.20.1, my Roughly Enough Items doesn't show any recipe for Advanced Memory Card from Better P2P, so i had to make one via kubejs to use it as intended.
Minecraft 1.20.1
Mod Loader : Neo Forge 47.1.100
Java : Eclipse Adoptium 17 (Latest Release)

I do not know if a log is needed, but you can ask me for one down below

Edit: i do not know if it's intended this way tho

**Comment by LasmGratel** [comment]
[Modrinth](https://modrinth.com/mod/betterp2p) has a newer version that fixes this problem
