### ISSUE TITLE
The textures are lost

### ISSUE THREAD

**Issue by magcicada** [LasmGratel/BetterP2P#3]
Just like this:
![2022-04-28_10 37 45](https://user-images.githubusercontent.com/45464670/165665653-b45cd391-3f67-457a-8462-5ae0534f6246.png)
the lastset version with PAE2.

**Comment by magcicada** [comment]
And this:
![2022-04-28_10 44 01](https://user-images.githubusercontent.com/45464670/165666288-d35e7489-5a6b-4935-9554-b257ac6a51b5.png)

**Comment by magcicada** [comment]
There are 2 changes cause the issue:
https://github.com/LasmGratel/BetterP2P/commit/8362ece2e104247fa04bc55bbcde7ccfe3652604#diff-3b5905a0bc7645d0b364b15215c26881898303e9956ce166fc6eee676b852148R18
https://github.com/LasmGratel/BetterP2P/commit/8362ece2e104247fa04bc55bbcde7ccfe3652604#diff-2ca7f6d85e35fdc00dc169cbbf3bf0c13d70c093c8250dd70a87667a773ba488R145

**Comment by NorthHusky** [comment]
Mods:
appliedenergistics2-rv6-stable-7-extended_life-v0.52.8
betterp2p-1.12.2-1.2.2-extended_life
Forgelin-1.8.3
![image](https://user-images.githubusercontent.com/105886827/171994729-7000f1ce-8de5-4744-bcd5-1657b1e7c552.png)

**Comment by LasmGratel** [comment]
Fixed in the 1.2.3 version, thanks @Xikaro
