### ISSUE TITLE
Server disconnect when trying to bind

### ISSUE THREAD

**Issue by Traister101** [LasmGratel/BetterP2P#5]
Same issue as #1 due to your packets seemly doing nothing. I had a similar packet issue recently with an addon I am developing which was due to only testing in Creative. The reason that mattered is my item renaming system only ran on the client which **only** in creative mode can work at all (although with jank). 

Your [packet](https://github.com/LasmGratel/BetterP2P/blob/master/src/main/java/com/projecturanus/betterp2p/network/C2SUpdateInfo.kt) doesn't seem to do anything which is a problem seeing as it's the only way I saw for the client to modify the server from the GUI (which is required to bind the P2P tunnels). 

You ideally call a method from the packet to update the server such as this [packet](https://github.com/Traister101/Sacks-and-Such/blob/master/src/main/java/mod/traister101/sacks/network/RenamePacket.java) from my addon. It's sent from the client through a GUI and it carries a string for the item to be named. It calls a method in my server container (you don't have one of these) which renames the item. 

Now I should say that I haven't spent more than 10 min trying to figure out what's going wrong and while I have used Java enough to feel confident to some degree but I've never used Kotlin and 10 min really isn't anywhere near enough to act like I know the codebase perfectly but it stinks of the same issue I was having which I only solved cause I asked more experienced modders if they had any idea what I was doing wrong. 

Now for how to reproduce. 

1. Connect to a dedicated server (least that's what I've been playing on)
2. Use a Better Memory Card on a network with valid P2P tunnels
3. Select a P2P tunnel
4. Bind the selected P2P tunnel to another tunnel
5. Get disconnected.

I don't happen to have a easy log file to provide you (and the part you care about is the same as in #1) but my friend has told me the server has a panic attack when you attempt to Bind Tunnels via the Better Memory Card which only farther supports the idea that you are trying to bind them on the client rather than on the server

**Comment by sivaDog** [comment]
Has this issue been resolved?
I am looking forward to update the MOD!
