### ISSUE TITLE
Feature Request: Add P2P in-game tunnel item name to description?

### ISSUE THREAD

**Issue by sfcmgr** [LasmGratel/BetterP2P#6]
Would it be possible to add the in-game P2P tunnel item itself to the binding selection GUI please?

It seems like the description is set here https://github.com/LasmGratel/BetterP2P/blob/AE2-Omnifactory/src/main/java/com/projecturanus/betterp2p/client/gui/InfoWrapper.kt

with

`append("P2P ")`

At the moment you can't tell what sort of P2P device you are selecting, and a huge advantage would be renaming the object in-game with an anvil so you could at a glance see what you are connecting, not just needing to use frequency and location.

This would be especially useful for the AE2 GTEU P2P where you need to connect the correct voltages together and connecting to the wrong P2P could end up with explosions.

Does it seem like a good and possible change to replaced the fixed P2P text with the tunnels in-game name? This presumably would also help localisation, unless they are always called P2P everywhere, but I'd guess languages which are not Latin based may have a different abbreviation?

Thanks!

**Comment by LasmGratel** [comment]
lgtm


________________________________
From: chrisshearing ***@***.***>
Sent: Sunday, August 21, 2022 3:20:10 PM
To: LasmGratel/BetterP2P ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LasmGratel/BetterP2P] Feature Request: Add P2P in-game tunnel item name to description? (Issue #6)


Would it be possible to add the in-game P2P tunnel item itself to the binding selection GUI please?

It seems like the description is set here https://github.com/LasmGratel/BetterP2P/blob/AE2-Omnifactory/src/main/java/com/projecturanus/betterp2p/client/gui/InfoWrapper.kt

with

append("P2P ")

At the moment you can't tell what sort of P2P device you are selecting, and a huge advantage would be renaming the object in-game with an anvil so you could at a glance see what you are connecting, not just needing to use frequency and location.

This would be especially useful for the AE2 GTEU P2P where you need to connect the correct voltages together and connecting to the wrong P2P could end up with explosions.

Does it seem like a good and possible change to replaced the fixed P2P text with the tunnels in-game name? This presumably would also help localisation, unless they are always called P2P everywhere, but I'd guess languages which are not Latin based may have a different abbreviation?

Thanks!

**Comment by LasmGratel** [comment]
sorry for a very late reply, but it is currently unimplemented due to a strange limitation of injecting the "Renaming Capability" to P2P devices. I will look into AE2's code in the next few days.

**Comment by sfcmgr** [comment]
No need to apologise at all! Thank you very much for looking at implementing the request!

**Comment by Vej-sys** [comment]
is this still being worked on?
