### ISSUE TITLE
增加孤立p2p提示

### ISSUE THREAD

**Issue by YaoerWu** [LasmGratel/BetterP2P#7]
在工具gui中高亮提示网络中的孤立p2p频道（没有配对输入输出的频道）

**Comment by LasmGratel** [comment]
咕咕time


________________________________
From: A125 ***@***.***>
Sent: Sunday, September 11, 2022 12:14:42 AM
To: LasmGratel/BetterP2P ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LasmGratel/BetterP2P] 增加孤立p2p提示 (Issue #7)


在工具gui中高亮提示网络中的孤立p2p频道（没有配对输入输出的频道）

―
