### ISSUE TITLE
[Question] Would it be possible to Port this to 1.20,1?

### ISSUE THREAD

**Issue by ByPyodaLP** [LasmGratel/BetterP2P#9]
Hey i enjoy the mod and i would like to include the advanced Memory Card into My 1.20,1 Modpack unfortunately this dosent support 1.20 yet Would you be so kind as to update it or give me a similar mod to work with

**Comment by aibgaming** [comment]
yes pls i would love to be able to use it atm9

**Comment by LasmGratel** [comment]
Coming right up, but expect bugs
